version: "3"
services:

  jdk8:
    image: sjj050121014/jdk8:1.0
    volumes:
      - .:/root
    command: sh run.sh  
 
  jdk7:
    image: sjj050121014/jdk7:1.0
    volumes:
      - .:/root
    command: sh run.sh
